# Generated by Django 6.1.1 on 2026-09-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredendpoint',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('error', 'Error')], max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.monitoredendpoint')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
