# Generated by Django 6.1.1 on 2026-09-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoredendpoint_timeout_seconds_healthcheckresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredendpoint',
            name='check_interval_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Minimum minutes between automatic due checks.'),
        ),
    ]
