# Generated by Django 6.1.1 on 2026-09-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoredendpoint_check_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredendpoint',
            name='alert_on_failure',
            field=models.BooleanField(default=True, help_text='Send alerts when status transitions to down/error or recovers.'),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Optional webhook notified on failure and recovery transitions.'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failure', 'Failure'), ('recovery', 'Recovery')], max_length=16)),
                ('channel', models.CharField(choices=[('webhook', 'Webhook')], default='webhook', max_length=16)),
                ('target', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.healthcheckresult')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoredendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
