# Generated by Django 6.1.1 on 2026-09-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoredendpoint_alert_on_failure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='alert_email',
            field=models.EmailField(blank=True, help_text='Optional email notified on failure and recovery transitions.', max_length=254),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Include this endpoint on the public status page.'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='channel',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email')], default='webhook', max_length=16),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.monitoredendpoint')),
                ('opened_by_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_incidents', to='monitoring.healthcheckresult')),
                ('resolved_by_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to='monitoring.healthcheckresult')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='endpoints', to='monitoring.tag'),
        ),
    ]
