# Generated by Django 6.1.1 on 2026-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_tag_monitoredendpoint_alert_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredendpoint',
            name='check_ssl_expiry',
            field=models.BooleanField(default=False, help_text='For HTTPS URLs, fail when the certificate expires within ssl_warn_days.'),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='expect_body_contains',
            field=models.CharField(blank=True, help_text='If set, response body must contain this substring.', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='max_latency_ms',
            field=models.PositiveIntegerField(blank=True, help_text='If set, responses slower than this are marked down.', null=True),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='mute_alerts_until',
            field=models.DateTimeField(blank=True, help_text='While set and in the future, skip webhook/email (incidents still sync).', null=True),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='ssl_warn_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Days before SSL expiry to treat the endpoint as down.'),
        ),
    ]
