# Generated by Django 6.1.1 on 2026-09-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_assertions_ssl_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Apollo Status', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='Live health for publicly listed endpoints.', max_length=255)),
                ('support_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status page config',
                'verbose_name_plural': 'Status page config',
            },
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='auth_secret',
            field=models.CharField(blank=True, help_text='Bearer token, or basic-auth password.', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer token'), ('basic', 'Basic auth')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='auth_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='Optional Discord webhook for failure/recovery alerts.'),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='failure_threshold',
            field=models.PositiveSmallIntegerField(default=1, help_text='Consecutive failures required before alerting and opening an incident.'),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Optional HTTP headers sent with each probe (string map).'),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='slack_webhook_url',
            field=models.URLField(blank=True, help_text='Optional Slack incoming webhook for failure/recovery alerts.'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='channel',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('discord', 'Discord'), ('slack', 'Slack')], default='webhook', max_length=16),
        ),
    ]
