# Generated by Django 6.1.1 on 2026-09-21 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_probe_auth_threshold_channels_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='expect_header_name',
            field=models.CharField(blank=True, help_text='Optional response header name that must be present.', max_length=120),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='expect_header_value',
            field=models.CharField(blank=True, help_text='If set with expect_header_name, header value must match (case-insensitive).', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='expect_json_path',
            field=models.CharField(blank=True, help_text='Dot path into JSON body, e.g. data.status', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='expect_json_value',
            field=models.CharField(blank=True, help_text='Expected value at expect_json_path (compared as string).', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_endpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='Daily quiet-hours end. Alerts muted inside the window.', null=True),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Daily quiet-hours start (local Django TIME_ZONE). Pair with quiet_hours_end.', null=True),
        ),
        migrations.AddField(
            model_name='monitoredendpoint',
            name='request_body',
            field=models.TextField(blank=True, help_text='Optional request body for POST/PUT/PATCH probes.'),
        ),
        migrations.AlterField(
            model_name='monitoredendpoint',
            name='mute_alerts_until',
            field=models.DateTimeField(blank=True, help_text='While set and in the future, skip alert channels (incidents still sync).', null=True),
        ),
    ]
